/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class example_list_t implements lcm.lcm.LCMEncodable
{
    public int n;
    public exlcm.example_t examples[];
 
    public example_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x350c81d61683c1c0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.example_list_t.class))
            return 0L;
 
        classes.add(exlcm.example_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + exlcm.example_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.n); 
 
        for (int a = 0; a < this.n; a++) {
            this.examples[a]._encodeRecursive(outs); 
        }
 
    }
 
    public example_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public example_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.example_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.example_list_t o = new exlcm.example_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.n = ins.readInt();
 
        this.examples = new exlcm.example_t[(int) n];
        for (int a = 0; a < this.n; a++) {
            this.examples[a] = exlcm.example_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public exlcm.example_list_t copy()
    {
        exlcm.example_list_t outobj = new exlcm.example_list_t();
        outobj.n = this.n;
 
        outobj.examples = new exlcm.example_t[(int) n];
        for (int a = 0; a < this.n; a++) {
            outobj.examples[a] = this.examples[a].copy();
        }
 
        return outobj;
    }
 
}

