/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class exampleconst_t implements lcm.lcm.LCMEncodable
{
 
    public exampleconst_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0000000012345678L;
 
    public static final int ABC = 1;
    public static final int DEF = 2;
    public static final double PI = 3.1415926;
    public static final double E = 2.8718;
    public static final long LONG = 0xf0f0f0f0L;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.exampleconst_t.class))
            return 0L;
 
        classes.add(exlcm.exampleconst_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
    }
 
    public exampleconst_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public exampleconst_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.exampleconst_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.exampleconst_t o = new exlcm.exampleconst_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
    }
 
    public exlcm.exampleconst_t copy()
    {
        exlcm.exampleconst_t outobj = new exlcm.exampleconst_t();
        return outobj;
    }
 
}

