/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package exlcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class node_t implements lcm.lcm.LCMEncodable
{
    public int num_children;
    public exlcm.node_t children[];
 
    public node_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x98ff4a363aeb7273L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(exlcm.node_t.class))
            return 0L;
 
        classes.add(exlcm.node_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + exlcm.node_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.num_children); 
 
        for (int a = 0; a < this.num_children; a++) {
            this.children[a]._encodeRecursive(outs); 
        }
 
    }
 
    public node_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public node_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static exlcm.node_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        exlcm.node_t o = new exlcm.node_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.num_children = ins.readInt();
 
        this.children = new exlcm.node_t[(int) num_children];
        for (int a = 0; a < this.num_children; a++) {
            this.children[a] = exlcm.node_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public exlcm.node_t copy()
    {
        exlcm.node_t outobj = new exlcm.node_t();
        outobj.num_children = this.num_children;
 
        outobj.children = new exlcm.node_t[(int) num_children];
        for (int a = 0; a < this.num_children; a++) {
            outobj.children[a] = this.children[a].copy();
        }
 
        return outobj;
    }
 
}

